document.writeln("<STYLE>");
document.writeln("A.menuitem {");
document.writeln("COLOR: menutext; TEXT-DECORATION: none");
document.writeln("}");
document.writeln("A.menuitem:hover {");
document.writeln("COLOR: highlighttext; BACKGROUND-COLOR: highlight");
document.writeln("}");
document.writeln("DIV.contextmenu {");
document.writeln("BORDER-RIGHT: 2px outset; BORDER-TOP: 2px outset; Z-INDEX: 999; VISIBILITY: hidden; BORDER-LEFT: 2px outset; BORDER-BOTTOM: 2px outset; POSITION: absolute; BACKGROUND-COLOR: buttonface");
document.writeln("}");
document.writeln("A.menuitem {");
document.writeln("COLOR: menutext; TEXT-DECORATION: none");
document.writeln("}");
document.writeln("A.menuitem:hover {");
document.writeln("COLOR: highlighttext; BACKGROUND-COLOR: highlight");
document.writeln("}");
document.writeln("DIV.contextmenu {");
document.writeln("BORDER-RIGHT: 2px outset; BORDER-TOP: 2px outset; Z-INDEX: 999; VISIBILITY: hidden; BORDER-LEFT: 2px outset; BORDER-BOTTOM: 2px outset; POSITION: absolute; BACKGROUND-COLOR: buttonface");
document.writeln("}<\/P><P><\/STYLE>");
document.writeln("<SCRIPT language=JavaScript>");
document.writeln("function Year_Month(){ ");
document.writeln("var now = new Date(); ");
document.writeln("var yy = now.getYear(); ");
document.writeln("var mm = now.getMonth()+1; ");
document.writeln("var cl = \'<font color=\"#0000df\">\'; ");
document.writeln("if (now.getDay() == 0) cl = \'<font color=\"#c00000\">\'; ");
document.writeln("if (now.getDay() == 6) cl = \'<font color=\"#00c000\">\'; ");
document.writeln("return(cl + yy + \'年\' + mm + \'月<\/font>\'); }");
document.writeln("function Date_of_Today(){ ");
document.writeln("var now = new Date(); ");
document.writeln("var cl = \'<font color=\"#ff0000\">\'; ");
document.writeln("if (now.getDay() == 0) cl = \'<font color=\"#c00000\">\'; ");
document.writeln("if (now.getDay() == 6) cl = \'<font color=\"#00c000\">\'; ");
document.writeln("return(cl + now.getDate() + \'<\/font>\'); }");
document.writeln("function Day_of_Today(){ ");
document.writeln("var day = new Array(); ");
document.writeln("day[0] = \"星期日\"; ");
document.writeln("day[1] = \"星期一\"; ");
document.writeln("day[2] = \"星期二\"; ");
document.writeln("day[3] = \"星期三\"; ");
document.writeln("day[4] = \"星期四\"; ");
document.writeln("day[5] = \"星期五\"; ");
document.writeln("day[6] = \"星期六\"; ");
document.writeln("var now = new Date();");
document.writeln("var cl = \'<font color=\"#0000df\">\'; ");
document.writeln("if (now.getDay() == 0) cl = \'<font color=\"#c00000\">\'; ");
document.writeln("if (now.getDay() == 6) cl = \'<font color=\"#00c000\">\'; ");
document.writeln("return(cl + day[now.getDay()] + \'<\/font>\'); }");
document.writeln("function CurentTime(){ ");
document.writeln("var now = new Date(); ");
document.writeln("var hh = now.getHours(); ");
document.writeln("var mm = now.getMinutes(); ");
document.writeln("var ss = now.getTime() % 60000; ");
document.writeln("ss = (ss - (ss % 1000)) \/ 1000; ");
document.writeln("var clock = hh+\':\'; ");
document.writeln("if (mm < 10) clock += \'0\'; ");
document.writeln("clock += mm+\':\'; ");
document.writeln("if (ss < 10) clock += \'0\'; ");
document.writeln("clock += ss; ");
document.writeln("return(clock); } ");
document.writeln("function refreshCalendarClock(){ ");
document.writeln("document.all.calendarClock1.innerHTML = Year_Month(); ");
document.writeln("document.all.calendarClock2.innerHTML = Date_of_Today(); ");
document.writeln("document.all.calendarClock3.innerHTML = Day_of_Today(); ");
document.writeln("document.all.calendarClock4.innerHTML = CurentTime(); }");
document.writeln("var webUrl = webUrl; ");
document.writeln("document.write(\'<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td>\'); ");
document.writeln("document.write(\'<table id=\"CalendarClockFreeCode\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"60\" height=\"70\" \');");
document.writeln("document.write(\'style=\"position:absolute;visibility:hidden\" bgcolor=\"#eeeeee\">\');");
document.writeln("document.write(\'<tr><td align=\"center\"><font \');");
document.writeln("document.write(\'style=\"cursor:hand;color:#ff0000;font-family:宋体;font-size:14pt;line-height:120%\" \');");
document.writeln("if (webUrl != \'netflower\'){ ");
document.writeln("document.write(\'<\/td><\/tr><tr><td align=\"center\"><font \');");
document.writeln("document.write(\'style=\"cursor:hand;color:#2000ff;font-family:宋体;font-size:12pt;line-height:110%\" \');");
document.writeln("} ");
document.writeln("document.write(\'<\/td><\/tr><\/table>\'); ");
document.writeln("document.write(\'<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"61\" bgcolor=\"#C0C0C0\" height=\"70\">\');");
document.writeln("document.write(\'<tr><td valign=\"top\" width=\"100%\" height=\"100%\">\');");
document.writeln("document.write(\'<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" width=\"120\" bgcolor=\"#FEFEEF\" height=\"150\">\');");
document.writeln("document.write(\'<tr><td align=\"center\" width=\"100%\" height=\"100%\" >\');");
document.writeln("document.write(\'<font id=\"calendarClock1\" style=\"font-family:宋体;font-size:12pt;line-height:120%\"> <\/font><br>\');");
document.writeln("document.write(\'<font id=\"calendarClock2\" style=\"color:#ff0000;font-family:Arial;font-size:25pt;line-height:120%\"> <\/font><br>\');");
document.writeln("document.write(\'<font id=\"calendarClock3\" style=\"font-family:宋体;font-size:13pt;line-height:120%\"> <\/font><br>\');");
document.writeln("document.write(\'<font id=\"calendarClock4\" style=\"color:#100080;font-family:宋体;font-size:12pt;line-height:120%\"><b> <\/b><\/font>\');");
document.writeln("document.write(\'<\/td><\/tr><\/table>\');");
document.writeln("document.write(\'<\/td><\/tr><\/table>\'); ");
document.writeln("document.write(\'<\/td><\/tr><\/table>\'); ");
document.writeln("setInterval(\'refreshCalendarClock()\',1000);");
document.writeln("<\/SCRIPT>")